### ISSUE TITLE
Use case

### ISSUE THREAD

**Issue by msocko420** [ashawkey/cubvh#12]
Ashawkey I first must say I follow your work religiously and can't thank you enough for your work. I was hoping you can give me a practical breakdown of cubvh in a practical use case for laments. Can I use this for improved mesh reconstruction or improved rendering in any of my existing 3D rendering pipelines?

**Comment by ashawkey** [comment]
@msocko420 Hi, thanks for your interest! This package is just a tool for querying point-to-mesh distance and performing raytracing. It may not directly improve on current projects.
