### ISSUE TITLE
Bug in setup.py

### ISSUE THREAD

**Issue by Khrylx** [ashawkey/cubvh#5]
https://github.com/ashawkey/cubvh/blob/main/setup.py#L39
This line will miss Eigen when the versions contain `0`, for example, Eigen 3.4.0.

**Comment by ashawkey** [comment]
@Khrylx Hi, do you have any suggestion to fix it? I remember to copy this part of code from [here](https://github.com/sxyu/sdf/blob/master/setup.py#L20).

**Comment by MrTornado24** [comment]
Same issue.

**Comment by Khrylx** [comment]
Hi, I suggest changing that line to:
```
if world_ver is None or major_ver is None or minor_ver is None:
```

**Comment by ashawkey** [comment]
thanks! I have fixed it in https://github.com/ashawkey/cubvh/commit/09648cf6c3a0b1b0a6f5a6e525d49ec387a3c99d
